### ISSUE TITLE
Phong material error

### ISSUE THREAD

**Issue by Sanekum** [glaretechnologies/blendigo#15]
After tweaking Roughness value on a newly created Phong material got this error when hit render:

Scene parsing error: Failed to find expected element 'diffuse_albedo_spectrum'.  (In element 'scene / material / phong'):
<phong>
	<roughness>
		<constant>0.6248354911804199</constant>
	</roughness>
	<f...

**Comment by theres1** [comment]
Can you provide blend file and versions of your OS, Blender, Blendigo, and Indigo? I have trouble reproducing this issue.

**Comment by Sanekum** [comment]
Sorry, it seams to be that my Indigo was outdated, 4.0.36.
4.2.14 works great.
Same with second issue
