### ISSUE TITLE
Instance geometry export error

### ISSUE THREAD

**Issue by Sanekum** [glaretechnologies/blendigo#17]
Group referenced objetcs export incorrect
Original geometry
![real-geometry](https://user-images.githubusercontent.com/26864751/37861443-9e276d80-2f5b-11e8-9be8-edb156a14b6e.jpg)

Group reference
![instance](https://user-images.githubusercontent.com/26864751/37861449-b37b8478-2f5b-11e8-84be-7930142923d9.jpg)

[Indigo_Instance_Bug.zip](https://github.com/glaretechnologies/blendigo/files/1844113/Indigo_Instance_Bug.zip)

Blender 2.79
Windows 10 x64
Indigo 4.2.14
Blendigo 4.0.14

**Comment by theres1** [comment]
I'll try to push an update preventing this from happening soon. But for now, I can tell you that you need to delete empty meshes: Fasade-window-1.6677, Plane.24076, Fasade-window-1.6674, Plane.24075.
They are the source of this strange behaviour.

**Comment by Sanekum** [comment]
Thanks a lot it realy solve my problem
