### ISSUE TITLE
Indigo RT and Indigo check

### ISSUE THREAD

**Issue by Zurkdahool** [glaretechnologies/blendigo#4]
Features which are only supported by IndigoRender should not be visible if Indigo RT is used. An automatic check when registering (loading)  blendigo in blender can check it automatically and hide options like SSS...

**Comment by Ono-Sendai** [comment]
They shouldn't be completely hidden, just disabled, perhaps with a note.
Otherwise it's confusing for the user when some controls are missing from the UI.
